

%%
LETTER = [a-zA-Z]
NONZERO_DIGIT = [1-9]
DIGIT = "0"|{NONZERO_DIGIT}


PROGRAM = {0PROGRAM} {ID} {DECLARATIONS_LIST} {PROCEDURE_LIST} {MAIN} {BLOCK} 
DECLARATIONS_LIST = {DECLARATIONS}|{DECLARATIONS_LIST}{DECLARATIONS}
}

%%
